"""
GICS Seed Data — Vollständige Hierarchie
Quelle: MSCI GICS Methodology, August 2024
163 Sub-Industries, 74 Industries, 25 Industry Groups, 11 Sektoren
"""

GICS_DATA = [
    # =========================================================
    # SEKTOR 10 — ENERGY
    # =========================================================
    {"sector_code": "10", "sector_name": "Energy",
     "industry_group_code": "1010", "industry_group_name": "Energy",
     "industry_code": "101010", "industry_name": "Energy Equipment & Services",
     "sub_industry_code": "10101010", "sub_industry_name": "Oil & Gas Drilling",
     "sub_industry_description": "Drilling contractors or owners of drilling rigs that contract their services for drilling wells."},
    {"sector_code": "10", "sector_name": "Energy",
     "industry_group_code": "1010", "industry_group_name": "Energy",
     "industry_code": "101010", "industry_name": "Energy Equipment & Services",
     "sub_industry_code": "10101020", "sub_industry_name": "Oil & Gas Equipment & Services",
     "sub_industry_description": "Manufacturers of equipment, including drilling rigs and equipment, and providers of supplies and services to oil, gas and consumable fuels operations."},
    {"sector_code": "10", "sector_name": "Energy",
     "industry_group_code": "1010", "industry_group_name": "Energy",
     "industry_code": "101020", "industry_name": "Oil, Gas & Consumable Fuels",
     "sub_industry_code": "10102010", "sub_industry_name": "Integrated Oil & Gas",
     "sub_industry_description": "Integrated oil companies engaged in the exploration & production of oil and gas, as well as at least one other significant activity in either refining, marketing and transportation, or chemicals."},
    {"sector_code": "10", "sector_name": "Energy",
     "industry_group_code": "1010", "industry_group_name": "Energy",
     "industry_code": "101020", "industry_name": "Oil, Gas & Consumable Fuels",
     "sub_industry_code": "10102020", "sub_industry_name": "Oil & Gas Exploration & Production",
     "sub_industry_description": "Companies engaged in the exploration and production of oil and gas not classified elsewhere."},
    {"sector_code": "10", "sector_name": "Energy",
     "industry_group_code": "1010", "industry_group_name": "Energy",
     "industry_code": "101020", "industry_name": "Oil, Gas & Consumable Fuels",
     "sub_industry_code": "10102030", "sub_industry_name": "Oil & Gas Refining & Marketing",
     "sub_industry_description": "Companies engaged in the refining and marketing of oil, gas and/or refined products not classified in the Integrated Oil & Gas or Independent Power Producers & Energy Traders Sub-Industries."},
    {"sector_code": "10", "sector_name": "Energy",
     "industry_group_code": "1010", "industry_group_name": "Energy",
     "industry_code": "101020", "industry_name": "Oil, Gas & Consumable Fuels",
     "sub_industry_code": "10102040", "sub_industry_name": "Oil & Gas Storage & Transportation",
     "sub_industry_description": "Companies engaged in the storage and/or transportation of oil, gas and/or refined products."},
    {"sector_code": "10", "sector_name": "Energy",
     "industry_group_code": "1010", "industry_group_name": "Energy",
     "industry_code": "101020", "industry_name": "Oil, Gas & Consumable Fuels",
     "sub_industry_code": "10102050", "sub_industry_name": "Coal & Consumable Fuels",
     "sub_industry_description": "Companies primarily involved in the production and mining of coal, related products and other consumable fuels related to the generation of energy."},

    # =========================================================
    # SEKTOR 15 — MATERIALS
    # =========================================================
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151010", "industry_name": "Chemicals",
     "sub_industry_code": "15101010", "sub_industry_name": "Commodity Chemicals",
     "sub_industry_description": "Companies that primarily manufacture chemicals used in the production of other chemicals or materials."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151010", "industry_name": "Chemicals",
     "sub_industry_code": "15101020", "sub_industry_name": "Diversified Chemicals",
     "sub_industry_description": "Manufacturers of a diversified range of chemical products not classified in the Commodity Chemicals, Fertilizers & Agricultural Chemicals or Specialty Chemicals Sub-Industries."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151010", "industry_name": "Chemicals",
     "sub_industry_code": "15101030", "sub_industry_name": "Fertilizers & Agricultural Chemicals",
     "sub_industry_description": "Producers of fertilizers, pesticides, potash or other agriculture-related chemicals not classified elsewhere."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151010", "industry_name": "Chemicals",
     "sub_industry_code": "15101040", "sub_industry_name": "Industrial Gases",
     "sub_industry_description": "Manufacturers of industrial gases."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151010", "industry_name": "Chemicals",
     "sub_industry_code": "15101050", "sub_industry_name": "Specialty Chemicals",
     "sub_industry_description": "Companies that primarily manufacture chemicals used for value-added properties."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151020", "industry_name": "Construction Materials",
     "sub_industry_code": "15102010", "sub_industry_name": "Construction Materials",
     "sub_industry_description": "Manufacturers of construction materials including sand, gravel, cement, and similar products."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151030", "industry_name": "Containers & Packaging",
     "sub_industry_code": "15103010", "sub_industry_name": "Metal, Glass & Plastic Containers",
     "sub_industry_description": "Manufacturers of metal, glass or plastic containers."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151030", "industry_name": "Containers & Packaging",
     "sub_industry_code": "15103020", "sub_industry_name": "Paper & Plastic Packaging Products & Materials",
     "sub_industry_description": "Manufacturers of paper and cardboard containers and packaging."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151040", "industry_name": "Metals & Mining",
     "sub_industry_code": "15104010", "sub_industry_name": "Aluminum",
     "sub_industry_description": "Producers of aluminum and related products, including companies that mine or process bauxite and refine alumina."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151040", "industry_name": "Metals & Mining",
     "sub_industry_code": "15104020", "sub_industry_name": "Diversified Metals & Mining",
     "sub_industry_description": "Companies engaged in the diversified production or extraction of metals and minerals."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151040", "industry_name": "Metals & Mining",
     "sub_industry_code": "15104025", "sub_industry_name": "Copper",
     "sub_industry_description": "Companies involved primarily in copper ore mining."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151040", "industry_name": "Metals & Mining",
     "sub_industry_code": "15104030", "sub_industry_name": "Gold",
     "sub_industry_description": "Producers of gold and related products, including companies that mine or process gold and the South African finance houses."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151040", "industry_name": "Metals & Mining",
     "sub_industry_code": "15104040", "sub_industry_name": "Precious Metals & Minerals",
     "sub_industry_description": "Companies mining precious metals and minerals not classified in the Gold Sub-Industry."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151040", "industry_name": "Metals & Mining",
     "sub_industry_code": "15104045", "sub_industry_name": "Silver",
     "sub_industry_description": "Companies primarily involved in silver ore mining."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151040", "industry_name": "Metals & Mining",
     "sub_industry_code": "15104050", "sub_industry_name": "Steel",
     "sub_industry_description": "Producers of iron and steel and related products."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151050", "industry_name": "Paper & Forest Products",
     "sub_industry_code": "15105010", "sub_industry_name": "Forest Products",
     "sub_industry_description": "Manufacturers of timber and related wood products."},
    {"sector_code": "15", "sector_name": "Materials",
     "industry_group_code": "1510", "industry_group_name": "Materials",
     "industry_code": "151050", "industry_name": "Paper & Forest Products",
     "sub_industry_code": "15105020", "sub_industry_name": "Paper Products",
     "sub_industry_description": "Manufacturers of all grades of paper."},

    # =========================================================
    # SEKTOR 20 — INDUSTRIALS
    # =========================================================
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2010", "industry_group_name": "Capital Goods",
     "industry_code": "201010", "industry_name": "Aerospace & Defense",
     "sub_industry_code": "20101010", "sub_industry_name": "Aerospace & Defense",
     "sub_industry_description": "Manufacturers of civil or military aerospace and defense equipment, parts or products."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2010", "industry_group_name": "Capital Goods",
     "industry_code": "201020", "industry_name": "Building Products",
     "sub_industry_code": "20102010", "sub_industry_name": "Building Products",
     "sub_industry_description": "Manufacturers of building components and home improvement products and equipment."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2010", "industry_group_name": "Capital Goods",
     "industry_code": "201030", "industry_name": "Construction & Engineering",
     "sub_industry_code": "20103010", "sub_industry_name": "Construction & Engineering",
     "sub_industry_description": "Companies engaged in primarily non-residential construction."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2010", "industry_group_name": "Capital Goods",
     "industry_code": "201040", "industry_name": "Electrical Equipment",
     "sub_industry_code": "20104010", "sub_industry_name": "Electrical Components & Equipment",
     "sub_industry_description": "Companies that produce electric motors, electrical transformers, electrical wiring and cables, power transmission products and electrical equipment."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2010", "industry_group_name": "Capital Goods",
     "industry_code": "201040", "industry_name": "Electrical Equipment",
     "sub_industry_code": "20104020", "sub_industry_name": "Heavy Electrical Equipment",
     "sub_industry_description": "Manufacturers of power-generating equipment and other heavy electrical equipment."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2010", "industry_group_name": "Capital Goods",
     "industry_code": "201050", "industry_name": "Industrial Conglomerates",
     "sub_industry_code": "20105010", "sub_industry_name": "Industrial Conglomerates",
     "sub_industry_description": "Diversified industrial companies with business activities in three or more sectors, none of which contributes a majority of revenues."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2010", "industry_group_name": "Capital Goods",
     "industry_code": "201060", "industry_name": "Machinery",
     "sub_industry_code": "20106010", "sub_industry_name": "Construction Machinery & Heavy Transportation Equipment",
     "sub_industry_description": "Manufacturers of heavy duty trucks, rolling machinery, earth-moving and construction equipment, and manufacturers of related parts."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2010", "industry_group_name": "Capital Goods",
     "industry_code": "201060", "industry_name": "Machinery",
     "sub_industry_code": "20106015", "sub_industry_name": "Agricultural & Farm Machinery",
     "sub_industry_description": "Companies manufacturing agricultural machinery, farm equipment and their related parts."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2010", "industry_group_name": "Capital Goods",
     "industry_code": "201060", "industry_name": "Machinery",
     "sub_industry_code": "20106020", "sub_industry_name": "Industrial Machinery & Supplies & Components",
     "sub_industry_description": "Manufacturers of industrial machinery and industrial components."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2010", "industry_group_name": "Capital Goods",
     "industry_code": "201070", "industry_name": "Trading Companies & Distributors",
     "sub_industry_code": "20107010", "sub_industry_name": "Trading Companies & Distributors",
     "sub_industry_description": "Trading companies and other distributors of industrial equipment and products."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2020", "industry_group_name": "Commercial & Professional Services",
     "industry_code": "202010", "industry_name": "Commercial Services & Supplies",
     "sub_industry_code": "20201010", "sub_industry_name": "Commercial Printing",
     "sub_industry_description": "Companies providing commercial printing services."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2020", "industry_group_name": "Commercial & Professional Services",
     "industry_code": "202010", "industry_name": "Commercial Services & Supplies",
     "sub_industry_code": "20201050", "sub_industry_name": "Environmental & Facilities Services",
     "sub_industry_description": "Companies providing environmental and facilities maintenance services."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2020", "industry_group_name": "Commercial & Professional Services",
     "industry_code": "202010", "industry_name": "Commercial Services & Supplies",
     "sub_industry_code": "20201060", "sub_industry_name": "Office Services & Supplies",
     "sub_industry_description": "Providers of office services and manufacturers of office supplies and equipment."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2020", "industry_group_name": "Commercial & Professional Services",
     "industry_code": "202010", "industry_name": "Commercial Services & Supplies",
     "sub_industry_code": "20201070", "sub_industry_name": "Diversified Support Services",
     "sub_industry_description": "Companies primarily providing labor oriented support services to businesses and governments."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2020", "industry_group_name": "Commercial & Professional Services",
     "industry_code": "202010", "industry_name": "Commercial Services & Supplies",
     "sub_industry_code": "20201080", "sub_industry_name": "Security & Alarm Services",
     "sub_industry_description": "Companies providing security and protection services to business and personal clients."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2020", "industry_group_name": "Commercial & Professional Services",
     "industry_code": "202020", "industry_name": "Professional Services",
     "sub_industry_code": "20202010", "sub_industry_name": "Human Resource & Employment Services",
     "sub_industry_description": "Companies providing business support services relating to human capital management."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2020", "industry_group_name": "Commercial & Professional Services",
     "industry_code": "202020", "industry_name": "Professional Services",
     "sub_industry_code": "20202020", "sub_industry_name": "Research & Consulting Services",
     "sub_industry_description": "Companies primarily providing research and consulting services to businesses and governments."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2020", "industry_group_name": "Commercial & Professional Services",
     "industry_code": "202020", "industry_name": "Professional Services",
     "sub_industry_code": "20202030", "sub_industry_name": "Data Processing & Outsourced Services",
     "sub_industry_description": "Providers of commercial electronic data processing and/or business process outsourcing services."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2030", "industry_group_name": "Transportation",
     "industry_code": "203010", "industry_name": "Air Freight & Logistics",
     "sub_industry_code": "20301010", "sub_industry_name": "Air Freight & Logistics",
     "sub_industry_description": "Companies providing air freight transportation, courier and logistics services."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2030", "industry_group_name": "Transportation",
     "industry_code": "203020", "industry_name": "Passenger Airlines",
     "sub_industry_code": "20302010", "sub_industry_name": "Passenger Airlines",
     "sub_industry_description": "Companies providing primarily passenger air transportation."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2030", "industry_group_name": "Transportation",
     "industry_code": "203030", "industry_name": "Marine Transportation",
     "sub_industry_code": "20303010", "sub_industry_name": "Marine Transportation",
     "sub_industry_description": "Companies providing goods or passenger maritime transportation."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2030", "industry_group_name": "Transportation",
     "industry_code": "203040", "industry_name": "Ground Transportation",
     "sub_industry_code": "20304010", "sub_industry_name": "Rail Transportation",
     "sub_industry_description": "Companies providing primarily goods and passenger rail transportation."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2030", "industry_group_name": "Transportation",
     "industry_code": "203040", "industry_name": "Ground Transportation",
     "sub_industry_code": "20304020", "sub_industry_name": "Cargo Ground Transportation",
     "sub_industry_description": "Companies providing primarily goods ground transportation and trucking services."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2030", "industry_group_name": "Transportation",
     "industry_code": "203040", "industry_name": "Ground Transportation",
     "sub_industry_code": "20304030", "sub_industry_name": "Passenger Ground Transportation",
     "sub_industry_description": "Companies providing primarily passenger ground transportation and related services."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2030", "industry_group_name": "Transportation",
     "industry_code": "203050", "industry_name": "Transportation Infrastructure",
     "sub_industry_code": "20305010", "sub_industry_name": "Airport Services",
     "sub_industry_description": "Operators of airports and companies providing related services."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2030", "industry_group_name": "Transportation",
     "industry_code": "203050", "industry_name": "Transportation Infrastructure",
     "sub_industry_code": "20305020", "sub_industry_name": "Highways & Railtracks",
     "sub_industry_description": "Owners and operators of roads, tunnels and railtracks."},
    {"sector_code": "20", "sector_name": "Industrials",
     "industry_group_code": "2030", "industry_group_name": "Transportation",
     "industry_code": "203050", "industry_name": "Transportation Infrastructure",
     "sub_industry_code": "20305030", "sub_industry_name": "Marine Ports & Services",
     "sub_industry_description": "Owners and operators of marine ports and related services."},

    # =========================================================
    # SEKTOR 25 — CONSUMER DISCRETIONARY
    # =========================================================
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2510", "industry_group_name": "Automobiles & Components",
     "industry_code": "251010", "industry_name": "Automobile Components",
     "sub_industry_code": "25101010", "sub_industry_name": "Automotive Parts & Equipment",
     "sub_industry_description": "Manufacturers of parts and accessories for automobiles and motorcycles."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2510", "industry_group_name": "Automobiles & Components",
     "industry_code": "251010", "industry_name": "Automobile Components",
     "sub_industry_code": "25101020", "sub_industry_name": "Tires & Rubber",
     "sub_industry_description": "Manufacturers of tires and rubber."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2510", "industry_group_name": "Automobiles & Components",
     "industry_code": "251020", "industry_name": "Automobiles",
     "sub_industry_code": "25102010", "sub_industry_name": "Automobile Manufacturers",
     "sub_industry_description": "Companies that primarily manufacture passenger automobiles and light trucks."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2510", "industry_group_name": "Automobiles & Components",
     "industry_code": "251020", "industry_name": "Automobiles",
     "sub_industry_code": "25102020", "sub_industry_name": "Motorcycle Manufacturers",
     "sub_industry_description": "Companies that primarily manufacture motorcycles, scooters or three-wheelers."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2520", "industry_group_name": "Consumer Durables & Apparel",
     "industry_code": "252010", "industry_name": "Household Durables",
     "sub_industry_code": "25201010", "sub_industry_name": "Consumer Electronics",
     "sub_industry_description": "Manufacturers of consumer electronics products including TVs, home audio equipment, game consoles, digital cameras, and related products."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2520", "industry_group_name": "Consumer Durables & Apparel",
     "industry_code": "252010", "industry_name": "Household Durables",
     "sub_industry_code": "25201020", "sub_industry_name": "Home Furnishings",
     "sub_industry_description": "Manufacturers of soft home furnishings or furniture, including upholstery, carpets, wall-coverings and wallpaper."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2520", "industry_group_name": "Consumer Durables & Apparel",
     "industry_code": "252010", "industry_name": "Household Durables",
     "sub_industry_code": "25201030", "sub_industry_name": "Homebuilding",
     "sub_industry_description": "Residential construction companies. Includes manufacturers of prefabricated houses and semi-fixed manufactured homes."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2520", "industry_group_name": "Consumer Durables & Apparel",
     "industry_code": "252010", "industry_name": "Household Durables",
     "sub_industry_code": "25201040", "sub_industry_name": "Household Appliances",
     "sub_industry_description": "Manufacturers of electric household appliances and related products."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2520", "industry_group_name": "Consumer Durables & Apparel",
     "industry_code": "252010", "industry_name": "Household Durables",
     "sub_industry_code": "25201050", "sub_industry_name": "Housewares & Specialties",
     "sub_industry_description": "Manufacturers of durable household products, including cutlery, cookware, glassware, crystal, silverware, picture frames and other similar products."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2520", "industry_group_name": "Consumer Durables & Apparel",
     "industry_code": "252020", "industry_name": "Leisure Products",
     "sub_industry_code": "25202010", "sub_industry_name": "Leisure Products",
     "sub_industry_description": "Manufacturers of leisure products and equipment including sports equipment, bicycles and toys."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2520", "industry_group_name": "Consumer Durables & Apparel",
     "industry_code": "252030", "industry_name": "Textiles, Apparel & Luxury Goods",
     "sub_industry_code": "25203010", "sub_industry_name": "Apparel, Accessories & Luxury Goods",
     "sub_industry_description": "Manufacturers of apparel, accessories & luxury goods. Includes apparel manufacturers, designers, brand names as well as luxury goods including leather goods."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2520", "industry_group_name": "Consumer Durables & Apparel",
     "industry_code": "252030", "industry_name": "Textiles, Apparel & Luxury Goods",
     "sub_industry_code": "25203020", "sub_industry_name": "Footwear",
     "sub_industry_description": "Manufacturers of footwear."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2520", "industry_group_name": "Consumer Durables & Apparel",
     "industry_code": "252030", "industry_name": "Textiles, Apparel & Luxury Goods",
     "sub_industry_code": "25203030", "sub_industry_name": "Textiles",
     "sub_industry_description": "Manufacturers of textile and related products not classified in the Apparel, Accessories & Luxury Goods Sub-Industry."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2530", "industry_group_name": "Consumer Services",
     "industry_code": "253010", "industry_name": "Hotels, Restaurants & Leisure",
     "sub_industry_code": "25301010", "sub_industry_name": "Casinos & Gaming",
     "sub_industry_description": "Owners and operators of casinos and gaming facilities."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2530", "industry_group_name": "Consumer Services",
     "industry_code": "253010", "industry_name": "Hotels, Restaurants & Leisure",
     "sub_industry_code": "25301020", "sub_industry_name": "Hotels, Resorts & Cruise Lines",
     "sub_industry_description": "Owners and operators of hotels, resorts and cruise-ships."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2530", "industry_group_name": "Consumer Services",
     "industry_code": "253010", "industry_name": "Hotels, Restaurants & Leisure",
     "sub_industry_code": "25301030", "sub_industry_name": "Leisure Facilities",
     "sub_industry_description": "Owners and operators of leisure facilities, including fitness centers, golf courses, and resort properties."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2530", "industry_group_name": "Consumer Services",
     "industry_code": "253010", "industry_name": "Hotels, Restaurants & Leisure",
     "sub_industry_code": "25301040", "sub_industry_name": "Restaurants",
     "sub_industry_description": "Owners and operators of restaurants, bars, pubs, fast-food or take-out facilities."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2530", "industry_group_name": "Consumer Services",
     "industry_code": "253020", "industry_name": "Diversified Consumer Services",
     "sub_industry_code": "25302010", "sub_industry_name": "Education Services",
     "sub_industry_description": "Companies providing educational services, either on-line or through conventional teaching methods."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2530", "industry_group_name": "Consumer Services",
     "industry_code": "253020", "industry_name": "Diversified Consumer Services",
     "sub_industry_code": "25302020", "sub_industry_name": "Specialized Consumer Services",
     "sub_industry_description": "Companies providing consumer services not classified elsewhere."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2550", "industry_group_name": "Consumer Discretionary Distribution & Retail",
     "industry_code": "255010", "industry_name": "Distributors",
     "sub_industry_code": "25501010", "sub_industry_name": "Distributors",
     "sub_industry_description": "Distributors and wholesalers of general merchandise."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2550", "industry_group_name": "Consumer Discretionary Distribution & Retail",
     "industry_code": "255020", "industry_name": "Broadline Retail",
     "sub_industry_code": "25502020", "sub_industry_name": "Broadline Retail",
     "sub_industry_description": "Retailers offering a wide range of consumer discretionary merchandise."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2550", "industry_group_name": "Consumer Discretionary Distribution & Retail",
     "industry_code": "255030", "industry_name": "Specialty Retail",
     "sub_industry_code": "25503010", "sub_industry_name": "Apparel Retail",
     "sub_industry_description": "Retailers specializing mainly in apparel and accessories."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2550", "industry_group_name": "Consumer Discretionary Distribution & Retail",
     "industry_code": "255030", "industry_name": "Specialty Retail",
     "sub_industry_code": "25503020", "sub_industry_name": "Computer & Electronics Retail",
     "sub_industry_description": "Retailers specializing in computers, consumer electronics, and related products and services."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2550", "industry_group_name": "Consumer Discretionary Distribution & Retail",
     "industry_code": "255030", "industry_name": "Specialty Retail",
     "sub_industry_code": "25503030", "sub_industry_name": "Home Improvement Retail",
     "sub_industry_description": "Retailers offering home repair and improvement products and services."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2550", "industry_group_name": "Consumer Discretionary Distribution & Retail",
     "industry_code": "255030", "industry_name": "Specialty Retail",
     "sub_industry_code": "25503040", "sub_industry_name": "Other Specialty Retail",
     "sub_industry_description": "Retailers specializing in specific consumer products not classified elsewhere."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2550", "industry_group_name": "Consumer Discretionary Distribution & Retail",
     "industry_code": "255030", "industry_name": "Specialty Retail",
     "sub_industry_code": "25503050", "sub_industry_name": "Automotive Retail",
     "sub_industry_description": "Retailers specializing in automotive products, parts and services."},
    {"sector_code": "25", "sector_name": "Consumer Discretionary",
     "industry_group_code": "2550", "industry_group_name": "Consumer Discretionary Distribution & Retail",
     "industry_code": "255030", "industry_name": "Specialty Retail",
     "sub_industry_code": "25503060", "sub_industry_name": "Homefurnishing Retail",
     "sub_industry_description": "Retailers specializing in home furnishings, furniture, and related products."},

    # =========================================================
    # SEKTOR 30 — CONSUMER STAPLES
    # =========================================================
    {"sector_code": "30", "sector_name": "Consumer Staples",
     "industry_group_code": "3010", "industry_group_name": "Consumer Staples Distribution & Retail",
     "industry_code": "301010", "industry_name": "Consumer Staples Distribution & Retail",
     "sub_industry_code": "30101010", "sub_industry_name": "Drug Retail",
     "sub_industry_description": "Owners and operators of primarily drug retail stores and pharmacies."},
    {"sector_code": "30", "sector_name": "Consumer Staples",
     "industry_group_code": "3010", "industry_group_name": "Consumer Staples Distribution & Retail",
     "industry_code": "301010", "industry_name": "Consumer Staples Distribution & Retail",
     "sub_industry_code": "30101020", "sub_industry_name": "Food Distributors",
     "sub_industry_description": "Distributors of food products not classified in the Food Retail Sub-Industry."},
    {"sector_code": "30", "sector_name": "Consumer Staples",
     "industry_group_code": "3010", "industry_group_name": "Consumer Staples Distribution & Retail",
     "industry_code": "301010", "industry_name": "Consumer Staples Distribution & Retail",
     "sub_industry_code": "30101030", "sub_industry_name": "Food Retail",
     "sub_industry_description": "Owners and operators of primarily food retail stores and supermarkets."},
    {"sector_code": "30", "sector_name": "Consumer Staples",
     "industry_group_code": "3010", "industry_group_name": "Consumer Staples Distribution & Retail",
     "industry_code": "301010", "industry_name": "Consumer Staples Distribution & Retail",
     "sub_industry_code": "30101040", "sub_industry_name": "Consumer Staples Merchandise Retail",
     "sub_industry_description": "Retailers offering a wide range of consumer staples merchandise such as food, household, and personal care products."},
    {"sector_code": "30", "sector_name": "Consumer Staples",
     "industry_group_code": "3020", "industry_group_name": "Food, Beverage & Tobacco",
     "industry_code": "302010", "industry_name": "Beverages",
     "sub_industry_code": "30201010", "sub_industry_name": "Brewers",
     "sub_industry_description": "Producers of beer and malt liquors."},
    {"sector_code": "30", "sector_name": "Consumer Staples",
     "industry_group_code": "3020", "industry_group_name": "Food, Beverage & Tobacco",
     "industry_code": "302010", "industry_name": "Beverages",
     "sub_industry_code": "30201020", "sub_industry_name": "Distillers & Vintners",
     "sub_industry_description": "Distillers, vintners and producers of alcoholic beverages not classified in the Brewers Sub-Industry."},
    {"sector_code": "30", "sector_name": "Consumer Staples",
     "industry_group_code": "3020", "industry_group_name": "Food, Beverage & Tobacco",
     "industry_code": "302010", "industry_name": "Beverages",
     "sub_industry_code": "30201030", "sub_industry_name": "Soft Drinks & Non-alcoholic Beverages",
     "sub_industry_description": "Producers of non-alcoholic beverages including carbonated and non-carbonated soft drinks, fruit juices, teas, coffees and other non-alcoholic beverages."},
    {"sector_code": "30", "sector_name": "Consumer Staples",
     "industry_group_code": "3020", "industry_group_name": "Food, Beverage & Tobacco",
     "industry_code": "302020", "industry_name": "Food Products",
     "sub_industry_code": "30202010", "sub_industry_name": "Agricultural Products & Services",
     "sub_industry_description": "Producers of agricultural products. Includes crop growers, owners of plantations and companies that produce and process foods but do not package and market them."},
    {"sector_code": "30", "sector_name": "Consumer Staples",
     "industry_group_code": "3020", "industry_group_name": "Food, Beverage & Tobacco",
     "industry_code": "302020", "industry_name": "Food Products",
     "sub_industry_code": "30202030", "sub_industry_name": "Packaged Foods & Meats",
     "sub_industry_description": "Producers of packaged foods including dairy products, fruit juices, meats, poultry, fish and pet foods."},
    {"sector_code": "30", "sector_name": "Consumer Staples",
     "industry_group_code": "3020", "industry_group_name": "Food, Beverage & Tobacco",
     "industry_code": "302030", "industry_name": "Tobacco",
     "sub_industry_code": "30203010", "sub_industry_name": "Tobacco",
     "sub_industry_description": "Manufacturers of cigarettes and other tobacco products."},
    {"sector_code": "30", "sector_name": "Consumer Staples",
     "industry_group_code": "3030", "industry_group_name": "Household & Personal Products",
     "industry_code": "303010", "industry_name": "Household Products",
     "sub_industry_code": "30301010", "sub_industry_name": "Household Products",
     "sub_industry_description": "Producers of non-durable household products, including detergents, soaps, diapers and other tissue and household paper products."},
    {"sector_code": "30", "sector_name": "Consumer Staples",
     "industry_group_code": "3030", "industry_group_name": "Household & Personal Products",
     "industry_code": "303020", "industry_name": "Personal Care Products",
     "sub_industry_code": "30302010", "sub_industry_name": "Personal Care Products",
     "sub_industry_description": "Manufacturers of personal care and cosmetic products, including cosmetics and toiletries."},

    # =========================================================
    # SEKTOR 35 — HEALTH CARE
    # =========================================================
    {"sector_code": "35", "sector_name": "Health Care",
     "industry_group_code": "3510", "industry_group_name": "Health Care Equipment & Services",
     "industry_code": "351010", "industry_name": "Health Care Equipment & Supplies",
     "sub_industry_code": "35101010", "sub_industry_name": "Health Care Equipment",
     "sub_industry_description": "Manufacturers of health care equipment and devices. Includes medical instruments, drug delivery systems, cardiovascular & orthopedic devices, and diagnostic equipment."},
    {"sector_code": "35", "sector_name": "Health Care",
     "industry_group_code": "3510", "industry_group_name": "Health Care Equipment & Services",
     "industry_code": "351010", "industry_name": "Health Care Equipment & Supplies",
     "sub_industry_code": "35101020", "sub_industry_name": "Health Care Supplies",
     "sub_industry_description": "Manufacturers of health care supplies and medical products not classified elsewhere."},
    {"sector_code": "35", "sector_name": "Health Care",
     "industry_group_code": "3510", "industry_group_name": "Health Care Equipment & Services",
     "industry_code": "351020", "industry_name": "Health Care Providers & Services",
     "sub_industry_code": "35102010", "sub_industry_name": "Health Care Distributors",
     "sub_industry_description": "Distributors and wholesalers of health care products not classified elsewhere."},
    {"sector_code": "35", "sector_name": "Health Care",
     "industry_group_code": "3510", "industry_group_name": "Health Care Equipment & Services",
     "industry_code": "351020", "industry_name": "Health Care Providers & Services",
     "sub_industry_code": "35102015", "sub_industry_name": "Health Care Services",
     "sub_industry_description": "Providers of patient health care services not classified elsewhere."},
    {"sector_code": "35", "sector_name": "Health Care",
     "industry_group_code": "3510", "industry_group_name": "Health Care Equipment & Services",
     "industry_code": "351020", "industry_name": "Health Care Providers & Services",
     "sub_industry_code": "35102020", "sub_industry_name": "Health Care Facilities",
     "sub_industry_description": "Owners and operators of health care facilities, including hospitals, nursing homes, rehabilitation centers and animal hospitals."},
    {"sector_code": "35", "sector_name": "Health Care",
     "industry_group_code": "3510", "industry_group_name": "Health Care Equipment & Services",
     "industry_code": "351020", "industry_name": "Health Care Providers & Services",
     "sub_industry_code": "35102030", "sub_industry_name": "Managed Health Care",
     "sub_industry_description": "Owners and operators of Health Maintenance Organizations (HMOs) and other managed plans."},
    {"sector_code": "35", "sector_name": "Health Care",
     "industry_group_code": "3510", "industry_group_name": "Health Care Equipment & Services",
     "industry_code": "351030", "industry_name": "Health Care Technology",
     "sub_industry_code": "35103010", "sub_industry_name": "Health Care Technology",
     "sub_industry_description": "Companies providing information technology services primarily to health care providers."},
    {"sector_code": "35", "sector_name": "Health Care",
     "industry_group_code": "3520", "industry_group_name": "Pharmaceuticals, Biotechnology & Life Sciences",
     "industry_code": "352010", "industry_name": "Biotechnology",
     "sub_industry_code": "35201010", "sub_industry_name": "Biotechnology",
     "sub_industry_description": "Companies primarily engaged in the research, development, manufacturing and/or marketing of products based on genetic analysis and genetic engineering."},
    {"sector_code": "35", "sector_name": "Health Care",
     "industry_group_code": "3520", "industry_group_name": "Pharmaceuticals, Biotechnology & Life Sciences",
     "industry_code": "352020", "industry_name": "Pharmaceuticals",
     "sub_industry_code": "35202010", "sub_industry_name": "Pharmaceuticals",
     "sub_industry_description": "Companies engaged in the research, development or production of pharmaceuticals."},
    {"sector_code": "35", "sector_name": "Health Care",
     "industry_group_code": "3520", "industry_group_name": "Pharmaceuticals, Biotechnology & Life Sciences",
     "industry_code": "352030", "industry_name": "Life Sciences Tools & Services",
     "sub_industry_code": "35203010", "sub_industry_name": "Life Sciences Tools & Services",
     "sub_industry_description": "Companies enabling the drug discovery, development and production continuum by providing analytical tools, instruments, consumables & supplies, clinical trial services and contract research services."},

    # =========================================================
    # SEKTOR 40 — FINANCIALS
    # =========================================================
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4010", "industry_group_name": "Banks",
     "industry_code": "401010", "industry_name": "Banks",
     "sub_industry_code": "40101010", "sub_industry_name": "Diversified Banks",
     "sub_industry_description": "Large multinational banks or bank holding companies with highly diversified lines of business."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4010", "industry_group_name": "Banks",
     "industry_code": "401010", "industry_name": "Banks",
     "sub_industry_code": "40101015", "sub_industry_name": "Regional Banks",
     "sub_industry_description": "Commercial banks whose businesses are derived primarily from conventional domestic interest-based banking activities with a focus on retail clients."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4020", "industry_group_name": "Financial Services",
     "industry_code": "402010", "industry_name": "Diversified Financial Services",
     "sub_industry_code": "40201020", "sub_industry_name": "Other Diversified Financial Services",
     "sub_industry_description": "Providers of a diverse range of financial services and/or with some interest in a wide range of financial services."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4020", "industry_group_name": "Financial Services",
     "industry_code": "402010", "industry_name": "Diversified Financial Services",
     "sub_industry_code": "40201030", "sub_industry_name": "Multi-Sector Holdings",
     "sub_industry_description": "Companies with significant ownership interests in companies in three or more sectors, none of which contributes a majority of revenues."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4020", "industry_group_name": "Financial Services",
     "industry_code": "402010", "industry_name": "Diversified Financial Services",
     "sub_industry_code": "40201040", "sub_industry_name": "Specialized Finance",
     "sub_industry_description": "Companies engaged in specialized financial activities not classified elsewhere."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4020", "industry_group_name": "Financial Services",
     "industry_code": "402010", "industry_name": "Diversified Financial Services",
     "sub_industry_code": "40201050", "sub_industry_name": "Commercial & Residential Mortgage Finance",
     "sub_industry_description": "Financial companies providing mortgage financing for commercial and residential properties."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4020", "industry_group_name": "Financial Services",
     "industry_code": "402010", "industry_name": "Diversified Financial Services",
     "sub_industry_code": "40201060", "sub_industry_name": "Transaction & Payment Processing Services",
     "sub_industry_description": "Providers of transaction & payment processing services and related payment services."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4020", "industry_group_name": "Financial Services",
     "industry_code": "402020", "industry_name": "Consumer Finance",
     "sub_industry_code": "40202010", "sub_industry_name": "Consumer Finance",
     "sub_industry_description": "Providers of consumer finance services."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4020", "industry_group_name": "Financial Services",
     "industry_code": "402030", "industry_name": "Capital Markets",
     "sub_industry_code": "40203010", "sub_industry_name": "Asset Management & Custody Banks",
     "sub_industry_description": "Financial institutions primarily engaged in investment management and/or related custody and securities fee-based services."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4020", "industry_group_name": "Financial Services",
     "industry_code": "402030", "industry_name": "Capital Markets",
     "sub_industry_code": "40203020", "sub_industry_name": "Investment Banking & Brokerage",
     "sub_industry_description": "Financial institutions primarily engaged in investment banking & brokerage services."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4020", "industry_group_name": "Financial Services",
     "industry_code": "402030", "industry_name": "Capital Markets",
     "sub_industry_code": "40203030", "sub_industry_name": "Diversified Capital Markets",
     "sub_industry_description": "Financial institutions primarily engaged in diversified capital markets activities."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4020", "industry_group_name": "Financial Services",
     "industry_code": "402030", "industry_name": "Capital Markets",
     "sub_industry_code": "40203040", "sub_industry_name": "Financial Exchanges & Data",
     "sub_industry_description": "Financial exchanges for securities, commodities, and derivatives, and providers of financial decision support tools and products including financial information."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4020", "industry_group_name": "Financial Services",
     "industry_code": "402040", "industry_name": "Mortgage Real Estate Investment Trusts (REITs)",
     "sub_industry_code": "40204010", "sub_industry_name": "Mortgage REITs",
     "sub_industry_description": "Companies or trusts that service, originate, purchase and/or securitize residential and/or commercial mortgage loans."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4030", "industry_group_name": "Insurance",
     "industry_code": "403010", "industry_name": "Insurance",
     "sub_industry_code": "40301010", "sub_industry_name": "Insurance Brokers",
     "sub_industry_description": "Insurance and reinsurance brokerage firms."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4030", "industry_group_name": "Insurance",
     "industry_code": "403010", "industry_name": "Insurance",
     "sub_industry_code": "40301020", "sub_industry_name": "Life & Health Insurance",
     "sub_industry_description": "Companies offering primarily life reassurance and insurance."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4030", "industry_group_name": "Insurance",
     "industry_code": "403010", "industry_name": "Insurance",
     "sub_industry_code": "40301030", "sub_industry_name": "Multi-line Insurance",
     "sub_industry_description": "Insurance companies with diversified interests in life, health and property and casualty insurance."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4030", "industry_group_name": "Insurance",
     "industry_code": "403010", "industry_name": "Insurance",
     "sub_industry_code": "40301040", "sub_industry_name": "Property & Casualty Insurance",
     "sub_industry_description": "Companies offering primarily property and casualty insurance."},
    {"sector_code": "40", "sector_name": "Financials",
     "industry_group_code": "4030", "industry_group_name": "Insurance",
     "industry_code": "403010", "industry_name": "Insurance",
     "sub_industry_code": "40301050", "sub_industry_name": "Reinsurance",
     "sub_industry_description": "Companies primarily engaged in reinsurance."},

    # =========================================================
    # SEKTOR 45 — INFORMATION TECHNOLOGY
    # =========================================================
    {"sector_code": "45", "sector_name": "Information Technology",
     "industry_group_code": "4510", "industry_group_name": "Software & Services",
     "industry_code": "451020", "industry_name": "IT Services",
     "sub_industry_code": "45102010", "sub_industry_name": "IT Consulting & Other Services",
     "sub_industry_description": "Providers of information technology and systems integration services."},
    {"sector_code": "45", "sector_name": "Information Technology",
     "industry_group_code": "4510", "industry_group_name": "Software & Services",
     "industry_code": "451020", "industry_name": "IT Services",
     "sub_industry_code": "45102020", "sub_industry_name": "Internet Services & Infrastructure",
     "sub_industry_description": "Companies providing services and infrastructure for the internet industry including data centers and cloud networking and storage infrastructure."},
    {"sector_code": "45", "sector_name": "Information Technology",
     "industry_group_code": "4510", "industry_group_name": "Software & Services",
     "industry_code": "451030", "industry_name": "Software",
     "sub_industry_code": "45103010", "sub_industry_name": "Application Software",
     "sub_industry_description": "Companies engaged primarily in developing and producing software designed for specialized applications for the business or consumer market."},
    {"sector_code": "45", "sector_name": "Information Technology",
     "industry_group_code": "4510", "industry_group_name": "Software & Services",
     "industry_code": "451030", "industry_name": "Software",
     "sub_industry_code": "45103020", "sub_industry_name": "Systems Software",
     "sub_industry_description": "Companies engaged primarily in developing and producing systems and database software."},
    {"sector_code": "45", "sector_name": "Information Technology",
     "industry_group_code": "4520", "industry_group_name": "Technology Hardware & Equipment",
     "industry_code": "452010", "industry_name": "Communications Equipment",
     "sub_industry_code": "45201020", "sub_industry_name": "Communications Equipment",
     "sub_industry_description": "Manufacturers of communication equipment and products, including LANs, WANs, routers, telephones, switchboards and exchanges."},
    {"sector_code": "45", "sector_name": "Information Technology",
     "industry_group_code": "4520", "industry_group_name": "Technology Hardware & Equipment",
     "industry_code": "452020", "industry_name": "Technology Hardware, Storage & Peripherals",
     "sub_industry_code": "45202030", "sub_industry_name": "Technology Hardware, Storage & Peripherals",
     "sub_industry_description": "Manufacturers of cellular phones, personal computers, servers, electronic computer components and peripherals."},
    {"sector_code": "45", "sector_name": "Information Technology",
     "industry_group_code": "4520", "industry_group_name": "Technology Hardware & Equipment",
     "industry_code": "452030", "industry_name": "Electronic Equipment, Instruments & Components",
     "sub_industry_code": "45203010", "sub_industry_name": "Electronic Equipment & Instruments",
     "sub_industry_description": "Manufacturers of electronic instruments and related products, including analytical, medical and industrial instruments, and process control equipment."},
    {"sector_code": "45", "sector_name": "Information Technology",
     "industry_group_code": "4520", "industry_group_name": "Technology Hardware & Equipment",
     "industry_code": "452030", "industry_name": "Electronic Equipment, Instruments & Components",
     "sub_industry_code": "45203015", "sub_industry_name": "Electronic Components",
     "sub_industry_description": "Manufacturers of electronic components."},
    {"sector_code": "45", "sector_name": "Information Technology",
     "industry_group_code": "4520", "industry_group_name": "Technology Hardware & Equipment",
     "industry_code": "452030", "industry_name": "Electronic Equipment, Instruments & Components",
     "sub_industry_code": "45203020", "sub_industry_name": "Electronic Manufacturing Services",
     "sub_industry_description": "Producers of electronic equipment, primarily for the business market."},
    {"sector_code": "45", "sector_name": "Information Technology",
     "industry_group_code": "4520", "industry_group_name": "Technology Hardware & Equipment",
     "industry_code": "452030", "industry_name": "Electronic Equipment, Instruments & Components",
     "sub_industry_code": "45203030", "sub_industry_name": "Technology Distributors",
     "sub_industry_description": "Distributors of technology hardware and equipment."},
    {"sector_code": "45", "sector_name": "Information Technology",
     "industry_group_code": "4530", "industry_group_name": "Semiconductors & Semiconductor Equipment",
     "industry_code": "453010", "industry_name": "Semiconductors & Semiconductor Equipment",
     "sub_industry_code": "45301010", "sub_industry_name": "Semiconductor Materials & Equipment",
     "sub_industry_description": "Manufacturers of semiconductor equipment, including manufacturers of the raw material and equipment used in the solar power industry."},
    {"sector_code": "45", "sector_name": "Information Technology",
     "industry_group_code": "4530", "industry_group_name": "Semiconductors & Semiconductor Equipment",
     "industry_code": "453010", "industry_name": "Semiconductors & Semiconductor Equipment",
     "sub_industry_code": "45301020", "sub_industry_name": "Semiconductors",
     "sub_industry_description": "Designers and manufacturers of semiconductors and related products."},

    # =========================================================
    # SEKTOR 50 — COMMUNICATION SERVICES
    # =========================================================
    {"sector_code": "50", "sector_name": "Communication Services",
     "industry_group_code": "5010", "industry_group_name": "Telecommunication Services",
     "industry_code": "501010", "industry_name": "Diversified Telecommunication Services",
     "sub_industry_code": "50101010", "sub_industry_name": "Alternative Carriers",
     "sub_industry_description": "Providers of communications and high-density data transmission services primarily through a high bandwidth/fiber-optic cable network."},
    {"sector_code": "50", "sector_name": "Communication Services",
     "industry_group_code": "5010", "industry_group_name": "Telecommunication Services",
     "industry_code": "501010", "industry_name": "Diversified Telecommunication Services",
     "sub_industry_code": "50101020", "sub_industry_name": "Integrated Telecommunication Services",
     "sub_industry_description": "Operators of primarily fixed-line telecommunications networks and companies providing both wireless and fixed-line telecommunications services."},
    {"sector_code": "50", "sector_name": "Communication Services",
     "industry_group_code": "5010", "industry_group_name": "Telecommunication Services",
     "industry_code": "501020", "industry_name": "Wireless Telecommunication Services",
     "sub_industry_code": "50102010", "sub_industry_name": "Wireless Telecommunication Services",
     "sub_industry_description": "Providers of primarily cellular or wireless telecommunication services."},
    {"sector_code": "50", "sector_name": "Communication Services",
     "industry_group_code": "5020", "industry_group_name": "Media & Entertainment",
     "industry_code": "502010", "industry_name": "Media",
     "sub_industry_code": "50201010", "sub_industry_name": "Advertising",
     "sub_industry_description": "Companies providing advertising, marketing or public relations services."},
    {"sector_code": "50", "sector_name": "Communication Services",
     "industry_group_code": "5020", "industry_group_name": "Media & Entertainment",
     "industry_code": "502010", "industry_name": "Media",
     "sub_industry_code": "50201020", "sub_industry_name": "Broadcasting",
     "sub_industry_description": "Owners and operators of television or radio broadcasting systems, including programming."},
    {"sector_code": "50", "sector_name": "Communication Services",
     "industry_group_code": "5020", "industry_group_name": "Media & Entertainment",
     "industry_code": "502010", "industry_name": "Media",
     "sub_industry_code": "50201030", "sub_industry_name": "Cable & Satellite",
     "sub_industry_description": "Providers of cable or satellite television services."},
    {"sector_code": "50", "sector_name": "Communication Services",
     "industry_group_code": "5020", "industry_group_name": "Media & Entertainment",
     "industry_code": "502010", "industry_name": "Media",
     "sub_industry_code": "50201040", "sub_industry_name": "Publishing",
     "sub_industry_description": "Publishers of newspapers, magazines and books in print or electronic formats."},
    {"sector_code": "50", "sector_name": "Communication Services",
     "industry_group_code": "5020", "industry_group_name": "Media & Entertainment",
     "industry_code": "502020", "industry_name": "Entertainment",
     "sub_industry_code": "50202010", "sub_industry_name": "Movies & Entertainment",
     "sub_industry_description": "Companies that engage in producing and selling entertainment products and services, including companies engaged in the production, distribution and screening of movies and television shows, producers and distributors of music, entertainment software and interactive media and companies engaged in related entertainment activities."},
    {"sector_code": "50", "sector_name": "Communication Services",
     "industry_group_code": "5020", "industry_group_name": "Media & Entertainment",
     "industry_code": "502020", "industry_name": "Entertainment",
     "sub_industry_code": "50202020", "sub_industry_name": "Interactive Home Entertainment",
     "sub_industry_description": "Producers of interactive gaming products, including mobile gaming applications."},
    {"sector_code": "50", "sector_name": "Communication Services",
     "industry_group_code": "5020", "industry_group_name": "Media & Entertainment",
     "industry_code": "502030", "industry_name": "Interactive Media & Services",
     "sub_industry_code": "50203010", "sub_industry_name": "Interactive Media & Services",
     "sub_industry_description": "Companies engaging in content and information creation or distribution through proprietary platforms, where revenues are derived primarily through pay-per-click advertisements."},

    # =========================================================
    # SEKTOR 55 — UTILITIES
    # =========================================================
    {"sector_code": "55", "sector_name": "Utilities",
     "industry_group_code": "5510", "industry_group_name": "Utilities",
     "industry_code": "551010", "industry_name": "Electric Utilities",
     "sub_industry_code": "55101010", "sub_industry_name": "Electric Utilities",
     "sub_industry_description": "Companies that produce or distribute electricity. Includes both nuclear and non-nuclear facilities."},
    {"sector_code": "55", "sector_name": "Utilities",
     "industry_group_code": "5510", "industry_group_name": "Utilities",
     "industry_code": "551020", "industry_name": "Gas Utilities",
     "sub_industry_code": "55102010", "sub_industry_name": "Gas Utilities",
     "sub_industry_description": "Companies whose main charter is to distribute and transmit natural and manufactured gas."},
    {"sector_code": "55", "sector_name": "Utilities",
     "industry_group_code": "5510", "industry_group_name": "Utilities",
     "industry_code": "551030", "industry_name": "Multi-Utilities",
     "sub_industry_code": "55103010", "sub_industry_name": "Multi-Utilities",
     "sub_industry_description": "Utility companies with significantly diversified activities in addition to core electric utility, gas utility and/or water utility operations such that no single segment contributes a majority of revenues."},
    {"sector_code": "55", "sector_name": "Utilities",
     "industry_group_code": "5510", "industry_group_name": "Utilities",
     "industry_code": "551040", "industry_name": "Water Utilities",
     "sub_industry_code": "55104010", "sub_industry_name": "Water Utilities",
     "sub_industry_description": "Companies that purchase and redistribute water to the end-consumer."},
    {"sector_code": "55", "sector_name": "Utilities",
     "industry_group_code": "5510", "industry_group_name": "Utilities",
     "industry_code": "551050", "industry_name": "Independent Power and Renewable Electricity Producers",
     "sub_industry_code": "55105010", "sub_industry_name": "Independent Power Producers & Energy Traders",
     "sub_industry_description": "Companies that operate as Independent Power Producers (IPPs), Gas & Power Marketing & Trading Specialists and/or Integrated Energy Merchants."},
    {"sector_code": "55", "sector_name": "Utilities",
     "industry_group_code": "5510", "industry_group_name": "Utilities",
     "industry_code": "551050", "industry_name": "Independent Power and Renewable Electricity Producers",
     "sub_industry_code": "55105020", "sub_industry_name": "Renewable Electricity",
     "sub_industry_description": "Companies that engage in the generation and distribution of electricity using renewable sources including, but not limited to, solar power, hydropower, wind power, geothermal power and marine power."},

    # =========================================================
    # SEKTOR 60 — REAL ESTATE
    # =========================================================
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6010", "industry_group_name": "Equity Real Estate Investment Trusts (REITs)",
     "industry_code": "601010", "industry_name": "Diversified REITs",
     "sub_industry_code": "60101010", "sub_industry_name": "Diversified REITs",
     "sub_industry_description": "A company or Trust with significantly diversified operations across two or more property types."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6010", "industry_group_name": "Equity Real Estate Investment Trusts (REITs)",
     "industry_code": "601025", "industry_name": "Industrial REITs",
     "sub_industry_code": "60102510", "sub_industry_name": "Industrial REITs",
     "sub_industry_description": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of industrial properties."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6010", "industry_group_name": "Equity Real Estate Investment Trusts (REITs)",
     "industry_code": "601030", "industry_name": "Hotel & Resort REITs",
     "sub_industry_code": "60103010", "sub_industry_name": "Hotel & Resort REITs",
     "sub_industry_description": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of hotel and resort properties."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6010", "industry_group_name": "Equity Real Estate Investment Trusts (REITs)",
     "industry_code": "601040", "industry_name": "Office REITs",
     "sub_industry_code": "60104010", "sub_industry_name": "Office REITs",
     "sub_industry_description": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of office properties."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6010", "industry_group_name": "Equity Real Estate Investment Trusts (REITs)",
     "industry_code": "601050", "industry_name": "Health Care REITs",
     "sub_industry_code": "60105010", "sub_industry_name": "Health Care REITs",
     "sub_industry_description": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of properties serving the health care industry."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6010", "industry_group_name": "Equity Real Estate Investment Trusts (REITs)",
     "industry_code": "601060", "industry_name": "Residential REITs",
     "sub_industry_code": "60106010", "sub_industry_name": "Multi-Family Residential REITs",
     "sub_industry_description": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of apartment and multi-family housing properties."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6010", "industry_group_name": "Equity Real Estate Investment Trusts (REITs)",
     "industry_code": "601060", "industry_name": "Residential REITs",
     "sub_industry_code": "60106020", "sub_industry_name": "Single-Family Residential REITs",
     "sub_industry_description": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of single-family residential housing properties."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6010", "industry_group_name": "Equity Real Estate Investment Trusts (REITs)",
     "industry_code": "601070", "industry_name": "Retail REITs",
     "sub_industry_code": "60107010", "sub_industry_name": "Retail REITs",
     "sub_industry_description": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of shopping malls, outlet centers, neighborhood and community shopping centers."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6010", "industry_group_name": "Equity Real Estate Investment Trusts (REITs)",
     "industry_code": "601080", "industry_name": "Specialized REITs",
     "sub_industry_code": "60108010", "sub_industry_name": "Other Specialized REITs",
     "sub_industry_description": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of properties not classified elsewhere."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6010", "industry_group_name": "Equity Real Estate Investment Trusts (REITs)",
     "industry_code": "601080", "industry_name": "Specialized REITs",
     "sub_industry_code": "60108020", "sub_industry_name": "Self-Storage REITs",
     "sub_industry_description": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of self-storage properties."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6010", "industry_group_name": "Equity Real Estate Investment Trusts (REITs)",
     "industry_code": "601080", "industry_name": "Specialized REITs",
     "sub_industry_code": "60108030", "sub_industry_name": "Telecom Tower REITs",
     "sub_industry_description": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of telecom towers and related structures that support wireless telecommunications."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6010", "industry_group_name": "Equity Real Estate Investment Trusts (REITs)",
     "industry_code": "601080", "industry_name": "Specialized REITs",
     "sub_industry_code": "60108040", "sub_industry_name": "Timber REITs",
     "sub_industry_description": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of timberland and timber-related properties."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6010", "industry_group_name": "Equity Real Estate Investment Trusts (REITs)",
     "industry_code": "601080", "industry_name": "Specialized REITs",
     "sub_industry_code": "60108050", "sub_industry_name": "Data Center REITs",
     "sub_industry_description": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of data center properties."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6020", "industry_group_name": "Real Estate Management & Development",
     "industry_code": "602010", "industry_name": "Real Estate Management & Development",
     "sub_industry_code": "60201010", "sub_industry_name": "Diversified Real Estate Activities",
     "sub_industry_description": "Companies engaged in a diverse spectrum of real estate activities including real estate development & sales, real estate management, or real estate services."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6020", "industry_group_name": "Real Estate Management & Development",
     "industry_code": "602010", "industry_name": "Real Estate Management & Development",
     "sub_industry_code": "60201020", "sub_industry_name": "Real Estate Operating Companies",
     "sub_industry_description": "Companies engaged primarily in real estate operations not classified elsewhere."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6020", "industry_group_name": "Real Estate Management & Development",
     "industry_code": "602010", "industry_name": "Real Estate Management & Development",
     "sub_industry_code": "60201030", "sub_industry_name": "Real Estate Development",
     "sub_industry_description": "Companies that develop real estate and sell the properties after development. Excludes companies classified in the Homebuilding Sub-Industry."},
    {"sector_code": "60", "sector_name": "Real Estate",
     "industry_group_code": "6020", "industry_group_name": "Real Estate Management & Development",
     "industry_code": "602010", "industry_name": "Real Estate Management & Development",
     "sub_industry_code": "60201040", "sub_industry_name": "Real Estate Services",
     "sub_industry_description": "Real estate service providers such as real estate agents, brokers & valuers."},
]
